import { useState, useMemo } from 'react';
import { Users, Building2, Mail, Phone, MapPin, Plus, Search, Edit, Trash2, Eye, MoreVertical, ArrowUpDown } from 'lucide-react';
import { Card } from './ui/card';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Badge } from './ui/badge';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from './ui/dialog';
import { Label } from './ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from './ui/table';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from './ui/dropdown-menu';
import { Textarea } from './ui/textarea';
import { toast } from 'sonner';
import { UserRole, Customer } from '../types/pis';
import { usePIS } from '../context/PISContext';
import { getRolePermissions } from '../utils/permissions';

interface CustomersViewProps {
 currentRole: UserRole;
}
export function CustomersView({ currentRole }: CustomersViewProps) {
 const { customers, addCustomer, deleteCustomer } = usePIS();
 const permissions = getRolePermissions(currentRole);
 const [searchQuery, setSearchQuery] = useState('');
 const [statusFilter, setStatusFilter] = useState<string>('all');
 const [categoryFilter, setCategoryFilter] = useState<string>('all');
 const [isAddDialogOpen, setIsAddDialogOpen] = useState(false);
 const [isViewDialogOpen, setIsViewDialogOpen] = useState(false);
 const [selectedCustomer, setSelectedCustomer] = useState<Customer | null>(null);
 const [sortConfig, setSortConfig] = useState<{ key: keyof Customer; direction: 'asc' | 'desc' } | null>(null);

 // New customer form state
 const [newCustomer, setNewCustomer] = useState({
  name: '',
  company: '',
  email: '',
  phone: '',
  address: '',
  category: 'SMB' as Customer['category'],
 });

 // If context starts empty (fresh install), seed with initial mock customers once
 // Customers are now loaded from API

 // Filtered and sorted customers
 const filteredCustomers = useMemo(() => {
  const filtered = customers.filter(customer => {
   const matchesSearch = 
    customer.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
    customer.company.toLowerCase().includes(searchQuery.toLowerCase()) ||
    customer.email.toLowerCase().includes(searchQuery.toLowerCase());
   
   const matchesStatus = statusFilter === 'all' || customer.status === statusFilter;
   const matchesCategory = categoryFilter === 'all' || customer.category === categoryFilter;
   
   return matchesSearch && matchesStatus && matchesCategory;
  });

  if (sortConfig) {
   filtered.sort((a, b) => {
    const aVal = a[sortConfig.key];
    const bVal = b[sortConfig.key];
    
    if (aVal < bVal) return sortConfig.direction === 'asc' ? -1 : 1;
    if (aVal > bVal) return sortConfig.direction === 'asc' ? 1 : -1;
    return 0;
   });
  }

  return filtered;
 }, [customers, searchQuery, statusFilter, categoryFilter, sortConfig]);

 const stats = useMemo(() => ({
  total: customers.length,
  active: customers.filter(c => c.status === 'ACTIVE').length,
  prospect: customers.filter(c => c.status === 'PROSPECT').length,
  totalPIS: customers.reduce((sum, c) => sum + c.totalPIS, 0),
 }), [customers]);

 const handleSort = (key: keyof Customer) => {
  setSortConfig(current => {
   if (current?.key === key) {
    return { key, direction: current.direction === 'asc' ? 'desc' : 'asc' };
   }
   return { key, direction: 'asc' };
  });
 };

 const handleAddCustomer = async () => {
  try {
   const customer: Customer = {
    id: '', // Will be generated by backend
    ...newCustomer,
    status: 'PROSPECT',
    totalPIS: 0,
    createdAt: new Date(),
   };
   
   await addCustomer(customer);
   setNewCustomer({ name: '', company: '', email: '', phone: '', address: '', category: 'SMB' });
   setIsAddDialogOpen(false);
   toast.success('Customer added successfully');
  } catch (error) {
   toast.error(error instanceof Error ? error.message : 'Failed to add customer');
  }
 };

 const handleDeleteCustomer = async (id: string) => {
  try {
   await deleteCustomer(id);
   toast.success('Customer deleted successfully');
  } catch (error) {
   toast.error(error instanceof Error ? error.message : 'Failed to delete customer');
  }
 };

 const getStatusBadge = (status: Customer['status']) => {
  const styles = {
   ACTIVE: 'bg-green-100 text-green-800',
   INACTIVE: 'bg-gray-100 text-gray-800',
   PROSPECT: 'bg-blue-100 text-blue-800',
  };
  return <Badge className={styles[status]}>{status}</Badge>;
 };

 const getCategoryBadge = (category: Customer['category']) => {
  const styles = {
   ENTERPRISE: 'bg-purple-100 text-purple-800',
   SMB: 'bg-gray-100 text-amber-800',
   STARTUP: 'bg-teal-100 text-teal-800',
  };
  return <Badge variant="outline" className={styles[category]}>{category}</Badge>;
 };

 return (
  <div className="space-y-6">
   {/* Header */}
   <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
    <div>
     <h2 className="text-3xl font-bold text-gray-900">Customer Management</h2>
     <p className="text-gray-600">Manage customer information and relationships</p>
    </div>
    {permissions.canManageCustomers && (
     <Button onClick={() => setIsAddDialogOpen(true)} className="flex items-center gap-2">
      <Plus className="h-4 w-4" />
      Add Customer
     </Button>
    )}
   </div>

   {/* Stats Cards */}
   <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
    <Card className="p-4">
     <div className="flex items-center gap-3">
      <div className="p-2 bg-blue-100 rounded-lg">
       <Users className="h-5 w-5 text-blue-600" />
      </div>
      <div>
       <p className="text-sm text-gray-500">Total Customers</p>
       <p className="text-2xl font-bold">{stats.total}</p>
      </div>
     </div>
    </Card>
    <Card className="p-4">
     <div className="flex items-center gap-3">
      <div className="p-2 bg-green-100 rounded-lg">
       <Users className="h-5 w-5 text-green-600" />
      </div>
      <div>
       <p className="text-sm text-gray-500">Active</p>
       <p className="text-2xl font-bold">{stats.active}</p>
      </div>
     </div>
    </Card>
    <Card className="p-4">
     <div className="flex items-center gap-3">
      <div className="p-2 bg-blue-100 rounded-lg">
       <Users className="h-5 w-5 text-blue-600" />
      </div>
      <div>
       <p className="text-sm text-gray-500">Prospects</p>
       <p className="text-2xl font-bold">{stats.prospect}</p>
      </div>
     </div>
    </Card>
    <Card className="p-4">
     <div className="flex items-center gap-3">
      <div className="p-2 bg-purple-100 rounded-lg">
       <Building2 className="h-5 w-5 text-purple-600" />
      </div>
      <div>
       <p className="text-sm text-gray-500">Total PIS</p>
       <p className="text-2xl font-bold">{stats.totalPIS}</p>
      </div>
     </div>
    </Card>
   </div>

   {/* Filters */}
   <Card className="p-4">
    <div className="flex flex-col md:flex-row gap-4">
     <div className="flex-1">
      <div className="relative">
       <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
       <Input
        placeholder="Search customers..."
        value={searchQuery}
        onChange={(e) => setSearchQuery(e.target.value)}
        className="pl-9"
       />
      </div>
     </div>
     <Select value={statusFilter} onValueChange={setStatusFilter}>
      <SelectTrigger className="w-full md:w-40">
       <SelectValue placeholder="Status" />
      </SelectTrigger>
      <SelectContent>
       <SelectItem value="all">All Status</SelectItem>
       <SelectItem value="ACTIVE">Active</SelectItem>
       <SelectItem value="INACTIVE">Inactive</SelectItem>
       <SelectItem value="PROSPECT">Prospect</SelectItem>
      </SelectContent>
     </Select>
     <Select value={categoryFilter} onValueChange={setCategoryFilter}>
      <SelectTrigger className="w-full md:w-40">
       <SelectValue placeholder="Category" />
      </SelectTrigger>
      <SelectContent>
       <SelectItem value="all">All Categories</SelectItem>
       <SelectItem value="ENTERPRISE">Enterprise</SelectItem>
       <SelectItem value="SMB">SMB</SelectItem>
       <SelectItem value="STARTUP">Startup</SelectItem>
      </SelectContent>
     </Select>
    </div>
   </Card>

   {/* Customer Table */}
   <Card className="overflow-hidden">
    <Table>
     <TableHeader>
      <TableRow>
       <TableHead className="cursor-pointer" onClick={() => handleSort('name')}>
        <div className="flex items-center gap-1">
         Customer
         <ArrowUpDown className="h-4 w-4" />
        </div>
       </TableHead>
       <TableHead>Contact</TableHead>
       <TableHead className="cursor-pointer" onClick={() => handleSort('status')}>
        <div className="flex items-center gap-1">
         Status
         <ArrowUpDown className="h-4 w-4" />
        </div>
       </TableHead>
       <TableHead>Category</TableHead>
       <TableHead className="cursor-pointer text-right" onClick={() => handleSort('totalPIS')}>
        <div className="flex items-center justify-end gap-1">
         PIS Count
         <ArrowUpDown className="h-4 w-4" />
        </div>
       </TableHead>
       <TableHead className="w-10"></TableHead>
      </TableRow>
     </TableHeader>
     <TableBody>
      {filteredCustomers.map((customer) => (
       <TableRow key={customer.id} className="hover:bg-gray-50">
        <TableCell>
         <div>
          <p className="font-medium text-gray-900">{customer.name}</p>
          <p className="text-sm text-gray-500">{customer.company}</p>
         </div>
        </TableCell>
        <TableCell>
         <div className="space-y-1">
          <p className="text-sm flex items-center gap-1">
           <Mail className="h-3 w-3" />
           {customer.email}
          </p>
          <p className="text-sm flex items-center gap-1 text-gray-500">
           <Phone className="h-3 w-3" />
           {customer.phone}
          </p>
         </div>
        </TableCell>
        <TableCell>{getStatusBadge(customer.status)}</TableCell>
        <TableCell>{getCategoryBadge(customer.category)}</TableCell>
        <TableCell className="text-right font-medium">{customer.totalPIS}</TableCell>
        <TableCell>
         <DropdownMenu>
          <DropdownMenuTrigger asChild>
           <Button variant="ghost" size="icon">
            <MoreVertical className="h-4 w-4" />
           </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
           <DropdownMenuItem onClick={() => { setSelectedCustomer(customer); setIsViewDialogOpen(true); }}>
            <Eye className="h-4 w-4 mr-2" />
            View Details
           </DropdownMenuItem>
           {permissions.canManageCustomers && (
            <>
             <DropdownMenuItem>
              <Edit className="h-4 w-4 mr-2" />
              Edit
             </DropdownMenuItem>
             <DropdownMenuItem 
              className="text-red-600"
              onClick={() => handleDeleteCustomer(customer.id)}
             >
              <Trash2 className="h-4 w-4 mr-2" />
              Delete
             </DropdownMenuItem>
            </>
           )}
          </DropdownMenuContent>
         </DropdownMenu>
        </TableCell>
       </TableRow>
      ))}
     </TableBody>
    </Table>
    
    {filteredCustomers.length === 0 && (
     <div className="p-8 text-center text-gray-500">
      No customers found matching your criteria
     </div>
    )}
   </Card>

   {/* Add Customer Dialog */}
   <Dialog open={isAddDialogOpen} onOpenChange={setIsAddDialogOpen}>
    <DialogContent className="max-w-md">
     <DialogHeader>
      <DialogTitle>Add New Customer</DialogTitle>
     </DialogHeader>
     <div className="space-y-4 py-4">
      <div className="space-y-2">
       <Label htmlFor="name">Contact Name</Label>
       <Input
        id="name"
        value={newCustomer.name}
        onChange={(e) => setNewCustomer(prev => ({ ...prev, name: e.target.value }))}
        placeholder="Enter contact name"
       />
      </div>
      <div className="space-y-2">
       <Label htmlFor="company">Company Name</Label>
       <Input
        id="company"
        value={newCustomer.company}
        onChange={(e) => setNewCustomer(prev => ({ ...prev, company: e.target.value }))}
        placeholder="Enter company name"
       />
      </div>
      <div className="space-y-2">
       <Label htmlFor="email">Email</Label>
       <Input
        id="email"
        type="email"
        value={newCustomer.email}
        onChange={(e) => setNewCustomer(prev => ({ ...prev, email: e.target.value }))}
        placeholder="Enter email address"
       />
      </div>
      <div className="space-y-2">
       <Label htmlFor="phone">Phone</Label>
       <Input
        id="phone"
        value={newCustomer.phone}
        onChange={(e) => setNewCustomer(prev => ({ ...prev, phone: e.target.value }))}
        placeholder="+91 XXXXX XXXXX"
       />
      </div>
      <div className="space-y-2">
       <Label htmlFor="address">Address</Label>
       <Textarea
        id="address"
        value={newCustomer.address}
        onChange={(e) => setNewCustomer(prev => ({ ...prev, address: e.target.value }))}
        placeholder="Enter address"
       />
      </div>
      <div className="space-y-2">
       <Label>Category</Label>
       <Select 
        value={newCustomer.category} 
        onValueChange={(v: Customer['category']) => setNewCustomer(prev => ({ ...prev, category: v }))}
       >
        <SelectTrigger>
         <SelectValue />
        </SelectTrigger>
        <SelectContent>
         <SelectItem value="ENTERPRISE">Enterprise</SelectItem>
         <SelectItem value="SMB">SMB</SelectItem>
         <SelectItem value="STARTUP">Startup</SelectItem>
        </SelectContent>
       </Select>
      </div>
     </div>
     <DialogFooter>
      <Button variant="outline" onClick={() => setIsAddDialogOpen(false)}>Cancel</Button>
      <Button onClick={handleAddCustomer}>Add Customer</Button>
     </DialogFooter>
    </DialogContent>
   </Dialog>

   {/* View Customer Dialog */}
   <Dialog open={isViewDialogOpen} onOpenChange={setIsViewDialogOpen}>
    <DialogContent className="max-w-lg">
     <DialogHeader>
      <DialogTitle>Customer Details</DialogTitle>
     </DialogHeader>
     {selectedCustomer && (
      <div className="space-y-4 py-4">
       <div className="flex items-center gap-4 p-4 bg-gray-50 rounded-lg">
        <div className="h-16 w-16 bg-blue-100 rounded-full flex items-center justify-center">
         <Users className="h-8 w-8 text-blue-600" />
        </div>
        <div>
         <h3 className="text-lg font-semibold">{selectedCustomer.name}</h3>
         <p className="text-gray-600">{selectedCustomer.company}</p>
        </div>
       </div>

       <div className="grid grid-cols-2 gap-4">
        <div className="space-y-1">
         <p className="text-sm text-gray-500">Status</p>
         {getStatusBadge(selectedCustomer.status)}
        </div>
        <div className="space-y-1">
         <p className="text-sm text-gray-500">Category</p>
         {getCategoryBadge(selectedCustomer.category)}
        </div>
       </div>

       <div className="space-y-3">
        <div className="flex items-center gap-2">
         <Mail className="h-4 w-4 text-gray-400" />
         <span>{selectedCustomer.email}</span>
        </div>
        <div className="flex items-center gap-2">
         <Phone className="h-4 w-4 text-gray-400" />
         <span>{selectedCustomer.phone}</span>
        </div>
        <div className="flex items-center gap-2">
         <MapPin className="h-4 w-4 text-gray-400" />
         <span>{selectedCustomer.address}</span>
        </div>
       </div>

       <div className="p-4 bg-blue-50 rounded-lg">
        <p className="text-sm text-blue-600">Total PIS Records</p>
        <p className="text-3xl font-bold text-blue-900">{selectedCustomer.totalPIS}</p>
       </div>

       <p className="text-sm text-gray-500">
        Customer since: {selectedCustomer.createdAt.toLocaleDateString()}
       </p>
      </div>
     )}
     <DialogFooter>
      <Button variant="outline" onClick={() => setIsViewDialogOpen(false)}>Close</Button>
     </DialogFooter>
    </DialogContent>
   </Dialog>
  </div>
 );
}
