import { useState, useMemo, useEffect } from 'react';
import { Package, Search, Plus, Eye, Edit, Trash2, MoreVertical, FlaskConical, Tag, ArrowUpDown } from 'lucide-react';
import { Card } from './ui/card';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Badge } from './ui/badge';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from './ui/dialog';
import { Label } from './ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from './ui/table';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from './ui/dropdown-menu';
import { Textarea } from './ui/textarea';
import { toast } from 'sonner';
import { UserRole, Product } from '../types/pis';
import { usePIS } from '../context/PISContext';
import { getRolePermissions } from '../utils/permissions';
import { EmptyState } from '../../ui/EmptyState';

interface ProductsViewProps {
 currentRole: UserRole;
}

export function ProductsView({ currentRole }: ProductsViewProps) {
 const { products, addProduct, updateProduct: _updateProduct, deleteProduct, isLoading: _isLoading } = usePIS();
 const permissions = getRolePermissions(currentRole);
 const [searchQuery, setSearchQuery] = useState('');
 const [statusFilter, setStatusFilter] = useState<string>('all');
 const [typeFilter, setTypeFilter] = useState<string>('all');
 const [categoryFilter, setCategoryFilter] = useState<string>('all');
 const [isAddDialogOpen, setIsAddDialogOpen] = useState(false);
 const [isViewDialogOpen, setIsViewDialogOpen] = useState(false);
 const [selectedProduct, setSelectedProduct] = useState<Product | null>(null);
 const [sortConfig, setSortConfig] = useState<{ key: keyof Product; direction: 'asc' | 'desc' } | null>(null);

 const [newProduct, setNewProduct] = useState({
  name: '',
  code: '',
  category: 'Skincare',
  type: 'CREAM' as Product['type'],
  ingredients: '',
  price: 0,
  description: '',
  imageUrl: '',
 });

 // If context starts empty (fresh install), seed with initial mock products once
 const [hasSeededDefaults, setHasSeededDefaults] = useState(false);

 useEffect(() => {
  if (!hasSeededDefaults && products.length === 0) {
   [].forEach((product) => addProduct(product));
   setHasSeededDefaults(true);
  }
 }, [hasSeededDefaults, products.length, addProduct]);

 const categories = useMemo(() =>
  [...new Set(products.map(p => p.category))],
  [products]
 );

 const filteredProducts = useMemo(() => {
  const result = products.filter(product => {
   const matchesSearch =
    product.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
    product.code.toLowerCase().includes(searchQuery.toLowerCase());

   const matchesStatus = statusFilter === 'all' || product.status === statusFilter;
   const matchesType = typeFilter === 'all' || product.type === typeFilter;
   const matchesCategory = categoryFilter === 'all' || product.category === categoryFilter;

   return matchesSearch && matchesStatus && matchesType && matchesCategory;
  });

  if (sortConfig) {
   result.sort((a, b) => {
    const aVal = a[sortConfig.key];
    const bVal = b[sortConfig.key];
    if (aVal == null || bVal == null) return 0;

    if (aVal < bVal) return sortConfig.direction === 'asc' ? -1 : 1;
    if (aVal > bVal) return sortConfig.direction === 'asc' ? 1 : -1;
    return 0;
   });
  }

  return result;
 }, [products, searchQuery, statusFilter, typeFilter, categoryFilter, sortConfig]);

 const stats = useMemo(() => ({
  total: products.length,
  active: products.filter(p => p.status === 'ACTIVE').length,
  development: products.filter(p => p.status === 'DEVELOPMENT').length,
  categories: categories.length,
 }), [products, categories]);

 const handleSort = (key: keyof Product) => {
  setSortConfig(current => {
   if (current?.key === key) {
    return { key, direction: current.direction === 'asc' ? 'desc' : 'asc' };
   }
   return { key, direction: 'asc' };
  });
 };

 const handleAddProduct = async () => {
  try {
   const product: Product = {
    id: '', // Will be generated by backend
    name: newProduct.name,
    code: newProduct.code,
    category: newProduct.category,
    type: newProduct.type,
    status: 'DEVELOPMENT',
    imageUrl: newProduct.imageUrl || undefined,
    ingredients: newProduct.ingredients.split(',').map(i => i.trim()).filter(i => i),
    price: newProduct.price,
    description: newProduct.description,
    createdAt: new Date(),
   };

   await addProduct(product);
   setNewProduct({ name: '', code: '', category: 'Skincare', type: 'CREAM', ingredients: '', price: 0, description: '', imageUrl: '' });
   setIsAddDialogOpen(false);
   toast.success('Product added successfully');
  } catch (error) {
   toast.error(error instanceof Error ? error.message : 'Failed to add product');
  }
 };

 const handleDeleteProduct = async (id: string) => {
  try {
   await deleteProduct(id);
   toast.success('Product deleted successfully');
  } catch (error) {
   toast.error(error instanceof Error ? error.message : 'Failed to delete product');
  }
 };

 const getStatusBadge = (status: Product['status']) => {
  const styles = {
   ACTIVE: 'bg-ok-soft text-ok',
   DEVELOPMENT: 'bg-surface-3 text-warn',
   DISCONTINUED: 'bg-surface-3 text-ink',
  };
  return <Badge className={styles[status]}>{status}</Badge>;
 };

 const getTypeBadge = (type: Product['type']) => {
  return <Badge variant="outline" className="text-xs">{type}</Badge>;
 };

 return (
  <div className="space-y-6">
   {/* Header */}
   <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
    <div>
     <h2 className="text-3xl font-bold text-ink">Product Catalog</h2>
     <p className="text-ink-2">Browse and manage product formulations</p>
    </div>
    <Button onClick={() => setIsAddDialogOpen(true)} className="flex items-center gap-2">
     <Plus className="h-4 w-4" />
     {permissions.canManageProducts && (
      <Button onClick={() => setIsAddDialogOpen(true)} className="flex items-center gap-2">
       <Plus className="h-4 w-4" />
       Add Product
      </Button>
     )}
    </Button>
   </div>

   {/* Stats Cards */}
   <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
    <Card className="p-4">
     <div className="flex items-center gap-3">
      <div className="p-2 bg-brand-soft rounded-lg">
       <Package className="h-5 w-5 text-brand" />
      </div>
      <div>
       <p className="text-sm text-ink-3">Total Products</p>
       <p className="text-2xl font-bold">{stats.total}</p>
      </div>
     </div>
    </Card>
    <Card className="p-4">
     <div className="flex items-center gap-3">
      <div className="p-2 bg-ok-soft rounded-lg">
       <Package className="h-5 w-5 text-ok" />
      </div>
      <div>
       <p className="text-sm text-ink-3">Active</p>
       <p className="text-2xl font-bold">{stats.active}</p>
      </div>
     </div>
    </Card>
    <Card className="p-4">
     <div className="flex items-center gap-3">
      <div className="p-2 bg-surface-3 rounded-lg">
       <FlaskConical className="h-5 w-5 text-ink" />
      </div>
      <div>
       <p className="text-sm text-ink-3">In Development</p>
       <p className="text-2xl font-bold">{stats.development}</p>
      </div>
     </div>
    </Card>
    <Card className="p-4">
     <div className="flex items-center gap-3">
      <div className="p-2 bg-purple-100 rounded-lg">
       <Tag className="h-5 w-5 text-purple-600" />
      </div>
      <div>
       <p className="text-sm text-ink-3">Categories</p>
       <p className="text-2xl font-bold">{stats.categories}</p>
      </div>
     </div>
    </Card>
   </div>

   {/* Filters */}
   <Card className="p-4">
    <div className="flex flex-col md:flex-row gap-4">
     <div className="flex-1">
      <div className="relative">
       <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-ink-4" />
       <Input
        placeholder="Search products..."
        value={searchQuery}
        onChange={(e) => setSearchQuery(e.target.value)}
        className="pl-9"
       />
      </div>
     </div>
     <Select value={statusFilter} onValueChange={setStatusFilter}>
      <SelectTrigger className="w-full md:w-36">
       <SelectValue placeholder="Status" />
      </SelectTrigger>
      <SelectContent>
       <SelectItem value="all">All Status</SelectItem>
       <SelectItem value="ACTIVE">Active</SelectItem>
       <SelectItem value="DEVELOPMENT">Development</SelectItem>
       <SelectItem value="DISCONTINUED">Discontinued</SelectItem>
      </SelectContent>
     </Select>
     <Select value={typeFilter} onValueChange={setTypeFilter}>
      <SelectTrigger className="w-full md:w-32">
       <SelectValue placeholder="Type" />
      </SelectTrigger>
      <SelectContent>
       <SelectItem value="all">All Types</SelectItem>
       <SelectItem value="CREAM">Cream</SelectItem>
       <SelectItem value="LOTION">Lotion</SelectItem>
       <SelectItem value="SERUM">Serum</SelectItem>
       <SelectItem value="GEL">Gel</SelectItem>
       <SelectItem value="OIL">Oil</SelectItem>
       <SelectItem value="POWDER">Powder</SelectItem>
      </SelectContent>
     </Select>
     <Select value={categoryFilter} onValueChange={setCategoryFilter}>
      <SelectTrigger className="w-full md:w-36">
       <SelectValue placeholder="Category" />
      </SelectTrigger>
      <SelectContent>
       <SelectItem value="all">All Categories</SelectItem>
       {categories.map(cat => (
        <SelectItem key={cat} value={cat}>{cat}</SelectItem>
       ))}
      </SelectContent>
     </Select>
    </div>
   </Card>

   {/* Products Table */}
   <Card className="overflow-hidden">
    <Table>
     <TableHeader>
      <TableRow>
       <TableHead>Photo</TableHead>
       <TableHead className="cursor-pointer" onClick={() => handleSort('name')}>
        <div className="flex items-center gap-1">
         Product
         <ArrowUpDown className="h-4 w-4" />
        </div>
       </TableHead>
       <TableHead>Code</TableHead>
       <TableHead>Category</TableHead>
       <TableHead>Type</TableHead>
       <TableHead className="cursor-pointer" onClick={() => handleSort('status')}>
        <div className="flex items-center gap-1">
         Status
         <ArrowUpDown className="h-4 w-4" />
        </div>
       </TableHead>
       <TableHead className="cursor-pointer text-right" onClick={() => handleSort('price')}>
        <div className="flex items-center justify-end gap-1">
         Price
         <ArrowUpDown className="h-4 w-4" />
        </div>
       </TableHead>
       <TableHead className="w-10"></TableHead>
      </TableRow>
     </TableHeader>
     <TableBody>
      {filteredProducts.map((product) => (
       <TableRow key={product.id} className="hover:bg-surface-2">
        <TableCell>
         <div className="h-10 w-10 rounded-lg overflow-hidden bg-brand-soft flex items-center justify-center">
          {(product as any).imageUrl ? (
           <img
            src={(product as any).imageUrl}
            alt={product.name}
            className="h-full w-full object-cover"
           />
          ) : (
           <Package className="h-5 w-5 text-brand" />
          )}
         </div>
        </TableCell>
        <TableCell>
         <div className="flex items-center gap-3">
          <div className="h-10 w-10 bg-brand-soft rounded-lg flex items-center justify-center">
           <Package className="h-5 w-5 text-brand" />
          </div>
          <div>
           <p className="font-medium text-ink">{product.name}</p>
           <p className="text-xs text-ink-3">{product.ingredients.slice(0, 3).join(', ')}</p>
          </div>
         </div>
        </TableCell>
        <TableCell className="font-mono text-sm">{product.code}</TableCell>
        <TableCell>{product.category}</TableCell>
        <TableCell>{getTypeBadge(product.type)}</TableCell>
        <TableCell>{getStatusBadge(product.status)}</TableCell>
        <TableCell className="text-right font-medium">₹{product.price.toLocaleString()}</TableCell>
        <TableCell>
         <DropdownMenu>
          <DropdownMenuTrigger asChild>
           <Button variant="ghost" size="icon">
            <MoreVertical className="h-4 w-4" />
           </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
           <DropdownMenuItem onClick={() => { setSelectedProduct(product); setIsViewDialogOpen(true); }}>
            <Eye className="h-4 w-4 mr-2" />
            View Details
           </DropdownMenuItem>
           {permissions.canManageProducts && (
            <>
             <DropdownMenuItem>
              <Edit className="h-4 w-4 mr-2" />
              Edit
             </DropdownMenuItem>
             <DropdownMenuItem
              className="text-err"
              onClick={() => handleDeleteProduct(product.id)}
             >
              <Trash2 className="h-4 w-4 mr-2" />
              Delete
             </DropdownMenuItem>
            </>
           )}
          </DropdownMenuContent>
         </DropdownMenu>
        </TableCell>
       </TableRow>
      ))}
     </TableBody>
    </Table>

    {filteredProducts.length === 0 && (
     <EmptyState icon={<Package />} title="No products found matching your criteria" />
    )}
   </Card>

   {/* Add Product Dialog */}
   <Dialog open={isAddDialogOpen} onOpenChange={setIsAddDialogOpen}>
    <DialogContent className="max-w-lg">
     <DialogHeader>
      <DialogTitle>Add New Product</DialogTitle>
     </DialogHeader>
     <div className="space-y-4 py-4 max-h-[60vh] overflow-y-auto">
      <div className="grid grid-cols-2 gap-4">
       <div className="space-y-2">
        <Label htmlFor="name">Product Name</Label>
        <Input
         id="name"
         value={newProduct.name}
         onChange={(e) => setNewProduct(prev => ({ ...prev, name: e.target.value }))}
         placeholder="Enter product name"
        />
       </div>
       <div className="space-y-2">
        <Label htmlFor="code">Product Code</Label>
        <Input
         id="code"
         value={newProduct.code}
         onChange={(e) => setNewProduct(prev => ({ ...prev, code: e.target.value.toUpperCase() }))}
         placeholder="e.g., ABC-001"
        />
       </div>
      </div>
      <div className="grid grid-cols-2 gap-4">
       <div className="space-y-2">
        <Label>Category</Label>
        <Select
         value={newProduct.category}
         onValueChange={(v) => setNewProduct(prev => ({ ...prev, category: v }))}
        >
         <SelectTrigger>
          <SelectValue />
         </SelectTrigger>
         <SelectContent>
          <SelectItem value="Skincare">Skincare</SelectItem>
          <SelectItem value="Hair Care">Hair Care</SelectItem>
          <SelectItem value="Sun Care">Sun Care</SelectItem>
          <SelectItem value="Body Care">Body Care</SelectItem>
          <SelectItem value="Men's Care">Men's Care</SelectItem>
         </SelectContent>
        </Select>
       </div>
       <div className="space-y-2">
        <Label>Type</Label>
        <Select
         value={newProduct.type}
         onValueChange={(v: Product['type']) => setNewProduct(prev => ({ ...prev, type: v }))}
        >
         <SelectTrigger>
          <SelectValue />
         </SelectTrigger>
         <SelectContent>
          <SelectItem value="CREAM">Cream</SelectItem>
          <SelectItem value="LOTION">Lotion</SelectItem>
          <SelectItem value="SERUM">Serum</SelectItem>
          <SelectItem value="GEL">Gel</SelectItem>
          <SelectItem value="OIL">Oil</SelectItem>
          <SelectItem value="POWDER">Powder</SelectItem>
          <SelectItem value="OTHER">Other</SelectItem>
         </SelectContent>
        </Select>
       </div>
      </div>
      <div className="space-y-2">
       <Label htmlFor="price">Price (₹)</Label>
       <Input
        id="price"
        type="number"
        value={newProduct.price}
        onChange={(e) => setNewProduct(prev => ({ ...prev, price: Number(e.target.value) }))}
        placeholder="0"
       />
      </div>
      <div className="space-y-2">
       <Label htmlFor="ingredients">Key Ingredients (comma separated)</Label>
       <Input
        id="ingredients"
        value={newProduct.ingredients}
        onChange={(e) => setNewProduct(prev => ({ ...prev, ingredients: e.target.value }))}
        placeholder="e.g., Vitamin C, Hyaluronic Acid, Niacinamide"
       />
      </div>
      <div className="space-y-2">
       <Label htmlFor="description">Description</Label>
       <Textarea
        id="description"
        value={newProduct.description}
        onChange={(e) => setNewProduct(prev => ({ ...prev, description: e.target.value }))}
        placeholder="Enter product description"
        rows={3}
       />
      </div>
     </div>
     <DialogFooter>
      <Button variant="outline" onClick={() => setIsAddDialogOpen(false)}>Cancel</Button>
      <Button onClick={handleAddProduct}>Add Product</Button>
     </DialogFooter>
    </DialogContent>
   </Dialog>

   {/* View Product Dialog */}
   <Dialog open={isViewDialogOpen} onOpenChange={setIsViewDialogOpen}>
    <DialogContent className="max-w-lg">
     <DialogHeader>
      <DialogTitle>Product Details</DialogTitle>
     </DialogHeader>
     {selectedProduct && (
      <div className="space-y-4 py-4">
       <div className="flex items-start gap-4 p-4 bg-brand-soft rounded-lg">
        <div className="h-16 w-16 bg-surface rounded-xl flex items-center justify-center shadow-sm">
         <Package className="h-8 w-8 text-brand" />
        </div>
        <div className="flex-1">
         <h3 className="text-lg font-semibold">{selectedProduct.name}</h3>
         <p className="font-mono text-sm text-ink-3">{selectedProduct.code}</p>
         <div className="flex gap-2 mt-2">
          {getStatusBadge(selectedProduct.status)}
          {getTypeBadge(selectedProduct.type)}
         </div>
        </div>
       </div>

       <div className="space-y-3">
        <div>
         <p className="text-sm font-medium text-ink-3 mb-1">Category</p>
         <p className="font-medium">{selectedProduct.category}</p>
        </div>
        <div>
         <p className="text-sm font-medium text-ink-3 mb-1">Description</p>
         <p className="text-ink-2">{selectedProduct.description}</p>
        </div>
        <div>
         <p className="text-sm font-medium text-ink-3 mb-2">Key Ingredients</p>
         <div className="flex flex-wrap gap-2">
          {selectedProduct.ingredients.map((ing, idx) => (
           <Badge key={idx} variant="outline" className="bg-ok-soft text-ok border-ok">
            {ing}
           </Badge>
          ))}
         </div>
        </div>
       </div>

       <div className="p-4 bg-brand-soft rounded-lg">
        <p className="text-sm text-brand">Price</p>
        <p className="text-3xl font-bold text-brand">₹{selectedProduct.price.toLocaleString()}</p>
       </div>

       <p className="text-sm text-ink-3">
        Added: {selectedProduct.createdAt.toLocaleDateString()}
       </p>
      </div>
     )}
     <DialogFooter>
      <Button variant="outline" onClick={() => setIsViewDialogOpen(false)}>Close</Button>
     </DialogFooter>
    </DialogContent>
   </Dialog>
  </div>
 );
}
