import { fieldDefs, type MasterPreviewSectionDef } from '../utils/masterSubmitPreview';

export const RM_PREVIEW_SECTIONS: MasterPreviewSectionDef[] = [
  {
    title: 'Primary info (details, code & Books)',
    fields: fieldDefs(
      [
        'rmSku',
        'zohoId',
        'sku',
        'subCategory',
        'optionalRmSubCategory',
        'rmCategory',
        'rmCategoryKey',
        'inciName',
        'tradeCommercialName',
        'functionRole',
        'rmType',
        'rmTaxPreference',
        'rmReturnable',
        'rmAssociateItems',
        'qcInspectionGroup',
        'hazardHandlingClass',
      ],
      {
        rmSku: 'Internal RM code (SKU)',
        inciName: 'INCI name',
        tradeCommercialName: 'Trade / commercial name',
        subCategory: 'Category',
        optionalRmSubCategory: 'Sub-category',
      }
    ),
  },
  {
    title: 'Units, Tax & Procurement',
    fields: fieldDefs(
      [
        'primaryUom',
        'issueUom',
        'standardPackSize',
        'hsnCode',
        'gst',
        'accountingCategory',
        'preferredCurrency',
        'grade',
        'compliance',
      ],
      { hsnCode: 'HSN / SAC', gst: 'GST %' }
    ),
  },
  {
    title: 'Technical & Regulatory',
    fields: fieldDefs([
      'casNo',
      'einecs',
      'countryOfOrigin',
      'manufacturer',
      'synonyms',
      'internalNotes',
      'allergenRequired',
      'gmoRequired',
      'sdsAvailable',
      'coaAvailable',
      'regulatoryNotes',
    ]),
  },
  {
    title: 'Quality Specifications',
    fields: fieldDefs([
      'assayPurity',
      'appearanceSpec',
      'phSpec',
      'moistureLod',
      'heavyMetalsSpec',
      'microbialSpec',
      'odorColorSpec',
      'otherSpecs',
    ]),
  },
  {
    title: 'Usage in Formulation (R&D)',
    fields: fieldDefs([
      'recommendedUseLevel',
      'maxUseLevel',
      'solubility',
      'processingGuidance',
      'incompatibilities',
      'stabilityNotes',
      'claims',
    ]),
  },
  {
    title: 'Vendors & Commercial',
    fields: [{ key: 'vendors', label: 'Vendors' }],
  },
  {
    title: 'QA Testing & Documents',
    fields: [
      { key: 'tests', label: 'QA tests' },
      { key: 'documents', label: 'Documents' },
    ],
  },
  {
    title: 'Inventory, Storage & WH',
    fields: fieldDefs([
      'rmDefaultStorageType',
      'storageConditions',
      'shelfLife',
      'retestPeriod',
      'warehouseLocation',
      'batchTracking',
      'fifoFefo',
      'minimumStock',
      'reorderLevel',
      'handlingNotes',
    ]),
  },
];

export const PM_PREVIEW_SECTIONS: MasterPreviewSectionDef[] = [
  {
    title: 'Primary info (details, code & tax)',
    fields: fieldDefs(
      [
        'itemCode',
        'name',
        'pmSkuCategory',
        'subCategory',
        'optionalPmSubCategory',
        'pmCategory',
        'itemCategory',
        'level',
        'status',
        'version',
        'zohoId',
        'pkgSku',
        'pkgUnit',
        'pkgHsn',
        'pkgGst',
        'pkgTaxPreference',
        'pkgReturnable',
        'pkgAssociateItems',
        'qcGroup',
        'storeLoc',
      ],
      {
        itemCode: 'Internal PM code (SKU)',
        pmSkuCategory: 'Category',
        optionalPmSubCategory: 'Sub-category',
        pkgHsn: 'HSN / SAC',
        pkgGst: 'GST %',
      }
    ),
  },
  {
    title: 'Technical, material & procurement',
    fields: fieldDefs([
      'intendedUse',
      'expectedProductTypes',
      'reusability',
      'regulatory',
      'identityNotes',
      'matBody',
      'matClosure',
      'matInner',
      'matRecycle',
      'matBpa',
      'matGrade',
      'specNominal',
      'specBrimful',
      'specHeight',
      'specDia',
      'specNeck',
      'specWeight',
      'specWall',
      'specLink',
      'assayPurity',
      'appearanceSpec',
      'phSpec',
      'moistureLod',
      'heavyMetalsSpec',
      'microbialSpec',
      'odorColorSpec',
      'otherSpecs',
    ]),
  },
  {
    title: 'Aesthetics',
    fields: fieldDefs(['colorType', 'colorCode', 'finish', 'deco', 'images']),
  },
  {
    title: 'Variants Matrix',
    fields: [{ key: 'variants', label: 'Variants' }],
  },
  {
    title: 'Customization & Tooling',
    fields: fieldDefs([
      'cusCustomizable',
      'cusParams',
      'cusStdMoq',
      'cusCustomMoq',
      'cusToolingReq',
      'cusToolingCost',
      'cusSamplingLT',
      'cusBulkLTStd',
      'cusBulkLTCustom',
      'cusRemarks',
    ]),
  },
  {
    title: 'Compatibility (R&D / QA)',
    fields: fieldDefs([
      'compLow',
      'compMed',
      'compHigh',
      'compOil',
      'compAlc',
      'compAirless',
      'compPump',
      'compLeak',
      'compActives',
      'compRisk',
      'compRemarks',
    ]),
  },
  {
    title: 'Vendors & Commercial',
    fields: [{ key: 'vendors', label: 'Vendors' }],
  },
  {
    title: 'Secondary Packaging',
    fields: fieldDefs([
      'secLabelType',
      'secLabelSize',
      'secAdhesive',
      'secLabelCompat',
      'secGsm',
      'secCartonFinish',
      'secFit',
      'secArtLink',
      'secNotes',
    ]),
  },
  {
    title: 'Tertiary Packaging',
    fields: fieldDefs(['terShipType', 'terUnits', 'terDrop', 'terStack', 'terNotes']),
  },
  {
    title: 'QA Testing & Documents',
    fields: [{ key: 'tests', label: 'QA tests' }],
  },
  {
    title: 'Catalogue / Website',
    fields: fieldDefs([
      'apprPack',
      'apprRd',
      'apprFin',
      'apprLock',
      'catVisible',
      'catShare',
      'catWebName',
      'catTags',
      'catRecoTypes',
      'catWebImages',
    ]),
  },
];

export const PR_PREVIEW_SECTIONS: MasterPreviewSectionDef[] = [
  {
    title: 'Primary info (details & Books)',
    fields: fieldDefs(
      [
        'productName',
        'category',
        'prSubCategory',
        'productForm',
        'brandClient',
        'fillSize',
        'packConfiguration',
        'skuCode',
        'prRecordType',
        'mrp',
        'zohoId',
        'skuForZoho',
        'bomTaxPreference',
        'bomReturnable',
        'bomAssociateItems',
        'bomCompositeItem',
        'prQcGroup',
        'prDefaultStorageType',
      ],
      {
        skuCode: 'Internal PR code',
        prRecordType: 'Record type',
        bomCompositeItem: 'Composite item',
      }
    ),
  },
  {
    title: 'Formula BOM',
    fields: [{ key: 'formulaIngredients', label: 'Formula BOM lines' }],
  },
  {
    title: 'SKU BOM (per unit)',
    fields: fieldDefs(['skuBomLimitQty', 'skuBomLimitUom'], {
      skuBomLimitQty: 'Net content per unit',
      skuBomLimitUom: 'Net content UoM',
    }).concat([{ key: 'skuBomLines', label: 'SKU BOM lines' }]),
  },
  {
    title: 'Pack BOM',
    fields: [{ key: 'packingComponents', label: 'Pack BOM lines' }],
  },
  {
    title: 'Process Steps',
    fields: [{ key: 'processSteps', label: 'Process steps' }],
  },
  {
    title: 'Specs & Regulatory',
    fields: fieldDefs([
      'phRange',
      'viscosity',
      'specificGravity',
      'appearance',
      'odour',
      'fillWeightSpec',
      'microbialLimits',
      'sppRating',
      'acceleratedStability',
      'intermediateStability',
      'longTermStability',
      'phototability',
      'freezeThawCycles',
      'applicableRegulation',
      'cosmosNaturalCertification',
      'dermatologicallyTested',
      'crueltyFreeVegan',
      'approvedMarketingClaims',
      'claimsSubstantiation',
    ]),
  },
];
