import type { QualityDevelopmentSectionConfig } from '../types/qualityDevelopments';

export const RM_QUALITY_DEVELOPMENTS: QualityDevelopmentSectionConfig = {
  key: 'rm',
  routeId: 'rm-developments',
  navLabel: 'RM Developments',
  pageTitle: 'RM Quality Developments',
  pageSubtitle: 'Raw material specification reviews, COA alignment, and release readiness.',
  scopeLabel: 'Raw Material',
  rows: [
    {
      id: 'rm-1',
      reference: 'QDEV-RM-2026-001',
      itemCode: '1000098',
      title: 'Hyaluronic Acid 1% — supplier change',
      category: 'Active Ingredient',
      status: 'In Review',
      assignee: 'Priya Sharma',
      requestedOn: '2026-03-12',
      targetDate: '2026-04-05',
      notes: 'Compare retained vs incoming COA; viscosity spec pending lab sign-off.',
    },
    {
      id: 'rm-2',
      reference: 'QDEV-RM-2026-002',
      itemCode: '1000142',
      title: 'Niacinamide USP — impurity profile update',
      category: 'Active Ingredient',
      status: 'Testing',
      assignee: 'Arjun Mehta',
      requestedOn: '2026-03-18',
      targetDate: '2026-04-12',
      notes: 'HPLC rerun scheduled; heavy metals within limit on draft report.',
    },
    {
      id: 'rm-3',
      reference: 'QDEV-RM-2026-003',
      itemCode: '2000031',
      title: 'Cetyl Alcohol — alternate vendor qualification',
      category: 'Excipient',
      status: 'Draft',
      assignee: 'Neha Iyer',
      requestedOn: '2026-03-22',
      targetDate: '2026-04-20',
      notes: 'Awaiting RM team to upload vendor spec sheet.',
    },
    {
      id: 'rm-4',
      reference: 'QDEV-RM-2026-004',
      itemCode: '1000205',
      title: 'Vitamin C stabilised — shelf-life extension study',
      category: 'Active Ingredient',
      status: 'Approved',
      assignee: 'Priya Sharma',
      requestedOn: '2026-02-08',
      targetDate: '2026-03-30',
      notes: 'Approved for production use; monitor first three GRN lots.',
    },
    {
      id: 'rm-5',
      reference: 'QDEV-RM-2026-005',
      itemCode: '2000088',
      title: 'Phenoxyethanol — preservative efficacy check',
      category: 'Preservative',
      status: 'On Hold',
      assignee: 'Arjun Mehta',
      requestedOn: '2026-03-01',
      targetDate: '2026-04-18',
      notes: 'On hold pending R&D reformulation decision.',
    },
  ],
};

export const PM_QUALITY_DEVELOPMENTS: QualityDevelopmentSectionConfig = {
  key: 'pm',
  routeId: 'pm-developments',
  navLabel: 'PM Developments',
  pageTitle: 'PM Quality Developments',
  pageSubtitle: 'Packaging artwork, dimensional checks, and GRN QC template updates.',
  scopeLabel: 'Packaging Material',
  rows: [
    {
      id: 'pm-1',
      reference: 'QDEV-PM-2026-001',
      itemCode: '5B00012',
      title: 'Airless pump 50 ml — crimp height validation',
      category: 'Primary Packaging',
      status: 'In Review',
      assignee: 'Kavita Desai',
      requestedOn: '2026-03-10',
      targetDate: '2026-04-02',
      notes: 'Sample lot #PM-4421; leak test protocol attached in master file.',
    },
    {
      id: 'pm-2',
      reference: 'QDEV-PM-2026-002',
      itemCode: '5B00045',
      title: 'Carton 60 ml — print registration tolerance',
      category: 'Secondary Packaging',
      status: 'Testing',
      assignee: 'Rahul Sinha',
      requestedOn: '2026-03-15',
      targetDate: '2026-04-08',
      notes: 'Colour delta review with marketing; barcode scan check passed.',
    },
    {
      id: 'pm-3',
      reference: 'QDEV-PM-2026-003',
      itemCode: '5B00078',
      title: 'Label film — adhesive migration study',
      category: 'Label',
      status: 'Draft',
      assignee: 'Kavita Desai',
      requestedOn: '2026-03-20',
      targetDate: '2026-04-22',
      notes: 'Vendor questionnaire sent; QC checklist draft in progress.',
    },
    {
      id: 'pm-4',
      reference: 'QDEV-PM-2026-004',
      itemCode: '5B00102',
      title: 'Induction seal wad — torque spec alignment',
      category: 'Closure',
      status: 'Approved',
      assignee: 'Rahul Sinha',
      requestedOn: '2026-02-20',
      targetDate: '2026-03-28',
      notes: 'Released to warehouse GRN QC template v2.1.',
    },
    {
      id: 'pm-5',
      reference: 'QDEV-PM-2026-005',
      itemCode: '5B00033',
      title: 'PET bottle 30 ml — wall thickness map',
      category: 'Primary Packaging',
      status: 'On Hold',
      assignee: 'Kavita Desai',
      requestedOn: '2026-03-05',
      targetDate: '2026-04-15',
      notes: 'Waiting for revised technical drawing from packaging vendor.',
    },
  ],
};

export const PIS_QUALITY_DEVELOPMENTS: QualityDevelopmentSectionConfig = {
  key: 'pis',
  routeId: 'pis-developments',
  navLabel: 'PIS Developments',
  pageTitle: 'PIS Quality Developments',
  pageSubtitle: 'Formulation and packaging quality gates for new product innovation submissions.',
  scopeLabel: 'PIS',
  rows: [
    {
      id: 'pis-1',
      reference: 'QDEV-PIS-2026-001',
      itemCode: 'PIS-2026-0142',
      title: 'Radiance Serum v3 — stability protocol',
      category: 'Formulation',
      status: 'In Review',
      assignee: 'Dr. Ananya Rao',
      requestedOn: '2026-03-08',
      targetDate: '2026-04-10',
      notes: 'Accelerated 40°C / 75% RH matrix; microbiology panel pending.',
    },
    {
      id: 'pis-2',
      reference: 'QDEV-PIS-2026-002',
      itemCode: 'PIS-2026-0156',
      title: 'Hydra Cream — claim substantiation pack',
      category: 'Claims & Documentation',
      status: 'Testing',
      assignee: 'Dr. Ananya Rao',
      requestedOn: '2026-03-14',
      targetDate: '2026-04-14',
      notes: 'Clinical summary under legal review; SPF not in scope.',
    },
    {
      id: 'pis-3',
      reference: 'QDEV-PIS-2026-003',
      itemCode: 'PIS-2026-0161',
      title: 'Sun Shield SPF 50 — PM artwork release',
      category: 'Packaging',
      status: 'Draft',
      assignee: 'Meera Kulkarni',
      requestedOn: '2026-03-19',
      targetDate: '2026-04-25',
      notes: 'Regulatory text blocks need QC wording approval.',
    },
    {
      id: 'pis-4',
      reference: 'QDEV-PIS-2026-004',
      itemCode: 'PIS-2026-0128',
      title: 'Clarifying Toner — preservative challenge',
      category: 'Microbiology',
      status: 'Approved',
      assignee: 'Dr. Ananya Rao',
      requestedOn: '2026-02-15',
      targetDate: '2026-03-25',
      notes: 'Cleared for pilot batch; monitor first commercial lot.',
    },
    {
      id: 'pis-5',
      reference: 'QDEV-PIS-2026-005',
      itemCode: 'PIS-2026-0170',
      title: 'Night Repair Oil — allergen declaration',
      category: 'Regulatory',
      status: 'On Hold',
      assignee: 'Meera Kulkarni',
      requestedOn: '2026-03-02',
      targetDate: '2026-04-18',
      notes: 'On hold until final fragrance allergen list from R&D.',
    },
  ],
};

export const QUALITY_DEVELOPMENT_SECTIONS: readonly QualityDevelopmentSectionConfig[] = [
  RM_QUALITY_DEVELOPMENTS,
  PM_QUALITY_DEVELOPMENTS,
  PIS_QUALITY_DEVELOPMENTS,
];

export function qualityDevelopmentSectionByRouteId(
  routeId: string,
): QualityDevelopmentSectionConfig | undefined {
  return QUALITY_DEVELOPMENT_SECTIONS.find((section) => section.routeId === routeId);
}
