import { createEmptyQualitySpecRow, type QualitySpecTableRow } from '../types/qualitySpecTable';

/** Default common-spec rows for bulk RM masters (cosmetic / skin-care template). */
export const RM_QUALITY_SPEC_TABLE_DEFAULTS: readonly Omit<QualitySpecTableRow, 'id'>[] = [
  {
    parameter: 'Appearance',
    specLimit: 'Per Master',
    method: 'Visual',
    mandatory: false,
    tolerance: 'Match',
    frequency: 'Per batch',
    sample: '10g',
    acceptance: 'Match',
    attachments: [],
  },
  {
    parameter: 'Color',
    specLimit: 'Per Master',
    method: 'Visual vs standard',
    mandatory: false,
    tolerance: 'Match',
    frequency: 'Per batch',
    sample: '10g',
    acceptance: 'Match',
    attachments: [],
  },
  {
    parameter: 'Odor',
    specLimit: 'Per Master',
    method: 'Olfactory',
    mandatory: false,
    tolerance: 'Match',
    frequency: 'Per batch',
    sample: '10g',
    acceptance: 'Match',
    attachments: [],
  },
  {
    parameter: 'pH',
    specLimit: 'Per Master',
    method: 'pH meter @25°C',
    mandatory: false,
    tolerance: '±0.3',
    frequency: 'Per batch',
    sample: '100g',
    acceptance: 'Within range',
    attachments: [],
  },
  {
    parameter: 'Viscosity',
    specLimit: 'Per Master (cps)',
    method: 'Brookfield @25°C',
    mandatory: false,
    tolerance: '±20%',
    frequency: 'Per batch',
    sample: '250g',
    acceptance: 'Within range',
    attachments: [],
  },
  {
    parameter: 'TAMC / TYMC',
    specLimit: '≤ 100 / 10 CFU/g',
    method: 'IS 14648',
    mandatory: false,
    tolerance: '≤ Limit',
    frequency: 'Per batch',
    sample: '1g',
    acceptance: 'Pass',
    attachments: [],
  },
  {
    parameter: 'Pathogens (E.coli/Salmonella/P.aeruginosa/S.aureus)',
    specLimit: 'Absent',
    method: 'IS 14648',
    mandatory: false,
    tolerance: 'Absent',
    frequency: 'Per batch',
    sample: '1g/10g',
    acceptance: 'Absent',
    attachments: [],
  },
  {
    parameter: 'Bulk Yield',
    specLimit: '≥ 95% of theoretical',
    method: 'Weigh',
    mandatory: false,
    tolerance: '≥ 95%',
    frequency: 'Per batch',
    sample: 'Full bulk',
    acceptance: '≥ 95%',
    attachments: [],
  },
  {
    parameter: 'Hold Time (bulk)',
    specLimit: '≤ 24 hr',
    method: 'BMR timestamp',
    mandatory: false,
    tolerance: '≤ 24 hr',
    frequency: 'Per batch',
    sample: 'BMR',
    acceptance: 'Within hold',
    attachments: [],
  },
];

export function cloneRmQualitySpecTableDefaults(): QualitySpecTableRow[] {
  return RM_QUALITY_SPEC_TABLE_DEFAULTS.map((row) => createEmptyQualitySpecRow(row));
}
