export const MODULE_ROUTE_MAP: Record<string, string> = {
  'dashboard': '/',
  'pis': '/pis',
  'order-management': '/procurement',
  'inventory': '/raw-material',
  'vendor-client': '/vendor-client',
  'treasury': '/treasury',
  'enquiry-management': '/enquiry-management',
  'task-management': '/task-management',
  'user-management': '/user-management',
  'role-management': '/role-management',
  'settings': '/settings',
  'catalogue-management': '/catalogue-management',
  'active-ingredients': '/active-ingredients',
  'customization-catalog': '/customization-catalog',
  'coupon-management': '/coupon-management',
  'discount-management': '/discount-management',
  'doctor-appointments': '/doctor-appointments',
  'contact-enquiry': '/contact-enquiry',
  'new-developments': '/new-developments',
  'product-samples': '/product-samples',
  'packaging-management': '/packaging-management',
};

export const ROUTE_MODULE_MAP: Record<string, string> = {
  '/': 'dashboard',
  '/pis': 'pis',
  '/procurement': 'order-management',
  '/warehouse': 'order-management',
  '/planning': 'order-management',
  '/production': 'order-management',
  '/fulfillment': 'order-management',
  '/client-hub': 'order-management',
  '/raw-material': 'inventory',
  '/packaging': 'inventory',
  '/bom': 'inventory',
  '/vendor-client': 'vendor-client',
  '/treasury': 'treasury',
  '/enquiry-management': 'enquiry-management',
  '/doctor-appointments': 'doctor-appointments',
  '/contact-enquiry': 'contact-enquiry',
  '/new-developments': 'new-developments',
  '/product-samples': 'product-samples',
  '/task-management': 'task-management',
  '/user-management': 'user-management',
  '/role-management': 'role-management',
  '/catalogue-management': 'catalogue-management',
  '/packaging-management': 'packaging-management',
  '/active-ingredients': 'active-ingredients',
  '/customization-catalog': 'active-ingredients',
  '/coupon-management': 'coupon-management',
  '/discount-management': 'discount-management',
};
